### ISSUE TITLE
Completion of first entry after Properties: not working with YAML templates

### ISSUE THREAD

**Issue by nimbusscale** [shalupov/idea-cloudformation#109]
For some reason when creating a resource such as:

```
  AlbSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: test
      GroupDescription: test
```

GroupName doesn't autocomplete.

If I reverse the two properties, GroupDescription doesn't auto complete, but GroupName does.

For whatever reason the first property is not being autocompleted. I can but a nonsense key/value pair as the first property and then everything after it works fine.

Simply putting an empty line after Properties, a key without a value or something that isn't a key/value pair doesn't doesn't seem to cause autocomplete to kick in. It seems like the plugin need to evaluate a key/value pair before it can do autocomplete for additional keys.
