### ISSUE TITLE
Support for CloudFormation inside serverless.yml

### ISSUE THREAD

**Issue by Birowsky** [shalupov/idea-cloudformation#112]
The Serverless Framework supports pretty much drop-in CloudFormation code:

https://serverless.com/framework/docs/providers/aws/guide/resources/

It'd be really nice if you could add support for serverless.yml files.

In short, anything within 
```
resources:
  Resources:
```
is CloudFormation.

**Comment by sweepy84** [comment]
+1 
Really need serverless types in there.

**Comment by shalupov** [comment]
That's well, a different language to support.
Not planned by me at this point, but contributions are welcome

**Comment by henhal** [comment]
Came here to suggest this and found this. 

A different language is perhaps exaggerating a bit. All that's needed is to enable the plugin for everything under `resources:` in files called `serverless.yml`.

**Comment by henhal** [comment]
@shalupov Any chance you might consider this? This is not about supporting a new language, only about _how the current file is recognized as containing CloudFormation code_. 

I have no prior plugin experience but tried to look at how this detection works without much success. If you open a .yaml file, the plugin seems to be activated as soon as the first line starts with `AWSTemplateFormatVersion: `. How is this accomplished?

As @Birowsky mentioned, what's needed for the cloud formation plugin to recognize also inline CF code inside serverless files is to also accept files called `serverless.yml` containing the lines:

```
resources:
  Resources:
    <CF code>
```

If needed, one could of course require some other magic marker such as the `AWSTemplateFormatVersion` line being present just before `Resources:` (if the SLS framework accepts that, otherwise perhaps as a comment `#AWSTemplateFormatVersion`?):

```
resources:
  AWSTemplateFormatVersion: '2012-09-01' # Treat everything from this level of indentation as a CF document
  Resources:
    <CF code>
```

There can be only one CF block in a serverless file, if that helps.

This would be extremely useful as it's painful to write CF blocks without any code-completion or other assistance. Granted, when using SLS, it's possible to extract CF to separate files and include them, but you then lose some of the superpowers of SLS, i.e., being able to use SLS variables inside CF blocks etc. And even if modularization and keeping many smaller files is often a good choice, in this case I think it tends to make my SLS files more messy.

If you would reconsider looking at this it would be so awesome, or perhaps give some pointers on where to start with a PR that adds support for detecting that a subset of a file is a CF block.

Thanks

**Comment by sgarner** [comment]
Came here to ask for this too. Would be a nice feature if the CF language support in this plugin could be injectable?

For now I'm just splitting CF templates out of the main serverless config to a separate file which then looks like a regular CF template and can be associated with this CF plugin:

```yml
# serverless.yml
service: foo
functions:
  ...
resources: ${file(resources.yml)}
```

```yml
# resources.yml
Resources:
  FooResource:
    Type: AWS::Foo::Bar
    Properties:
      Name: ${self:custom.name} # SLS variable
    ...
Outputs:
  Foo:
    Value: !Ref FooResource
    Description: ...
```

> Granted, when using SLS, it's possible to extract CF to separate files and include them, but you then lose some of the superpowers of SLS, i.e., being able to use SLS variables inside CF blocks etc.

SLS variables still work as normal inside the included file so this isn't a problem.
