### ISSUE TITLE
"Description" everywhere

### ISSUE THREAD

**Issue by kontrafiktion** [shalupov/idea-cloudformation#117]
Hi!

I have a CloudFormation template that has been generated by CodeStar.
Every resource has a "Description:" attribute. E.g.:

```
Resources:
  CodeBuildPolicy:
    Condition: CreateCodeBuildResources
    DependsOn: [CodeStarProject, CodeBuildRole]
    Description: Setting IAM policy for service role for Amazon EC2 instances
```
But "Description" is not recognized by the idea-cloudformation plugin.
I could not find any official documentation that says a "Description" attribute is allowed, but it obviously is.
