### ISSUE TITLE
Add support for Globals

### ISSUE THREAD

**Issue by winonone** [shalupov/idea-cloudformation#120]
Is it possible to support Global section for serverless transform? Like those mentioned in https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst

**Comment by dgorohov** [comment]
AWS made some changes to the serverless model as well several days ago: https://github.com/awslabs/serverless-application-model/releases/tag/1.4.0
As an example: `Cors` and `EndpointConfiguration ` are not supported by the plugin:
```
  Api:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref Environment
      Cors: "'*'"
      EndpointConfiguration: REGIONAL
      DefinitionBody:
        'Fn::Transform':
          Name: 'AWS::Include'
          Parameters:
            Location: !Sub s3://${BucketName}/api/swagger.yaml
```
