### ISSUE TITLE
Validation fails for AWS SAM templates if file is named cloudformation.yaml

### ISSUE THREAD

**Issue by matsev** [shalupov/idea-cloudformation#138]
Most times, the CloudFormation plugins works fine when configuring an AWS SAM template, e.g.

```
AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Resources:

  TestLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: index.handler
      Runtime: nodejs8.10
```

However, using the very same template in a file named `cloudformation.yaml` results in validation errors, see screenshots below:

![screen shot 2018-10-02 at 14 03 32](https://user-images.githubusercontent.com/234505/46347534-2677ce00-c64c-11e8-9f3c-12fb2bfecc61.png)

and 

![screen shot 2018-10-02 at 14 04 11](https://user-images.githubusercontent.com/234505/46347537-2972be80-c64c-11e8-9d92-3241fc5ff549.png)

---

IntelliJ IDEA 2018.2.4 (Ultimate Edition)
Build #IU-182.4505.22, built on September 18, 2018

AWS CloudFormation plugin version 0.5.69
