### ISSUE TITLE
YAML: !Select function marks !GetAZs as invalid argument

### ISSUE THREAD

**Issue by liwo** [shalupov/idea-cloudformation#96]
Example YAML code:
```
  Subnet:
    Type: 'AWS::EC2::Subnet'
    Properties:
      VpcId: !Ref Vpc
      CidrBlock: !Ref SubnetIpRange
      AvailabilityZone: !Select
        - '0'
        - !GetAZs
          Ref: 'AWS::Region'
```

This highlights the whole `!Select` function as error with message "Select expects an index argument and an array argument"

The code works just fine (`!GetAZs` returns an array), so the syntax error is bogus.
